### PR TITLE
Insert new subsets at (0, 0, 0)

### PR DESCRIPTION
**Pull request by JacquesLucke**
as requested by @mx1001

### CODE REVIEW

**Comment by JacquesLucke** [comment]
oops

**Comment by JacquesLucke** [comment]
ah the cutter is work in progress anyway xD

**Comment by niewinny** [comment]
@JacquesLucke 
just as a note for future, assign Jerry and let him make a merge, because we had a lot of problems with that before. :) 
its better when You will be the one doing the rebase

**Comment by JacquesLucke** [comment]
yes ok sry
I won't merge the next time.

**Comment by mx1001** [comment]
lol @ automerge. that was exciting haha.

**Pull request merged**
