### PR TITLE
Implement Basic structure for menu

### PR DESCRIPTION
**Pull request by JacquesLucke**
This is by far not complete but I'm not the right person to write the missing code because my I still have way to less knowledge about the different workflows.

Would be the best if you can try to understand the structure and check if it fits your needs. If not just tell me what needs to be different.

After you inserted the other layout code, I will look over it again and clean it up if necessary.
Please only use the object.hops.is_cstep etc functions instead of all the other variables that were previously used (is_bevel, is_bool, is_bevel_3, ....).

Also not that this pull request won't merge into your master branch directly but in a new branch I created called "Menu-Cleanup". Here we can finish the menu together before merging the changes into the master branch.

### CODE REVIEW

**Comment by niewinny** [comment]
ups that was not what I wanted to do lol

**Comment by niewinny** [comment]
can I fast forward to Your pull request  ?

**Comment by mx1001** [comment]
http://i.imgur.com/8E7Dgqc.gifv

left classic

right new.

**Comment by niewinny** [comment]
can You revert my last commit for that branch ?

**Comment by niewinny** [comment]
ok I reverted it manually merge it
so i will create new pull with menus done

**Pull request merged**
