### PR TITLE
Refactor message system and soft sharpener

### PR DESCRIPTION
**Pull request by JacquesLucke**

### CODE REVIEW

**Comment by JacquesLucke** [comment]
Here is an example how you have to change the code that shows the messages:
https://github.com/mx1001/HOps/commit/097809d87bdca963247bf7163e3ff00e5ee8b3d8

**Comment by JacquesLucke** [comment]
This implements a new "operators" folder, inside is a "sharpeners" folder and there is a new Soft Sharpen operator (should work like the old one but looks a bit nicer)
Would be nice if you can test it. current you have to call it using the spacebar menu and type "Soft Sharpen". If everything works fine you can replace it in the menus step by step. When it has been replaced everywhere we can remove the old implementation and start with the next operator.

**Comment by JacquesLucke** [comment]
I also implemented a preferences.py file. I think we should move the preferences stuff from the __init__ file into here

**Comment by JacquesLucke** [comment]
in the "graphics/drawing2d.py" module are a few utility functions for drawing on the viewport.
I used them in the new soft sharpen operator but they are generic enouph so that we can reuse them for other overlays or whatever comes to your mind.

**Comment by niewinny** [comment]
I just tested the new Soft sharpener and it looks awesome, though time stuff may be a little problematic, if we introduce the second one for Csharpen in the same place, tables will just overlay on each other.

Is there a way clear all stuff that has been drawn first before it time runs out and then draw it again . If that make sense.

So that way it will work like that
1. press Soft sharpener - it draws our table on screen
2. press Soft sharpener again(or other operator in future) - it clears previous one and then draw table on screen

**Comment by JacquesLucke** [comment]
So you just mean a function that disables/hides/removes all overlays that are visible at that moment?
Yes that is possible.

I'm working on the appending thing and rewrote parent_merge right now, afterwards I can implement that.

**Comment by niewinny** [comment]
Awesome to hear. 

Jerry introduced the naming for that so actually I have no idea what that shortcut from...

But in general we append 3 objects

1original one
2Plane to be used for rotation 
3 and extra box to be used for cutting

All have same name just with extra prefix
AP is for that plane
BB is for for that box

**Comment by JacquesLucke** [comment]
Yeah jerry explained me how it works already... I just had no idea why "AP" (Plane!? :D)
BB for bounding box is ok.

**Pull request merged**
