### PR TITLE
Initial Complex split boolean

### PR DESCRIPTION
**Pull request by JacquesLucke**
This does just simple cutting atm
nothing before and nothing afterwards (the modifiers will stay, but check out the code to see what it actually does)

cutting

I also removed the seperate_objects property. Reasons for that are that it doesn't work well with the poll function and that the user doesn't need it. The two parts will be selected after the operator, so if the user wants to join them he can just press *CTRL J*.

### CODE REVIEW

**Comment by mx1001** [comment]
it should separate by default. But keep them joined but split is the secondary behavior

**Comment by JacquesLucke** [comment]
oh really?
because in the operator was the default for *separate_objects* = *True*
or did I oversee something?

**Comment by niewinny** [comment]
that code was a total mess lol 
I tested it and it works like a charm

selection has to be kept at the cutting object though and all others needs to stay unselected, that is important part for the whole workflow.


keep in mind
we had there like 2 different cutters one using the old rebool behavior where it just splits with boolean modifier that behavior did not support  seperate_objects property 

and second one that is using solidify modifier first was using  seperate_objects property as simple slit for separated   meshes I don't think that there is a way in blender to actually support obj split in a way I would like to

**Comment by JacquesLucke** [comment]
oh ok.. 
I'll change it.

Just give me a list what needs to be added :)

**Comment by mx1001** [comment]
*separate_objects* =

*True*

*by default c split split the objects at the end. However AR made a
diffferent csplit that keeps it together. That was the alternate behavior. *

**Comment by niewinny** [comment]
ok so in general we can even remove the old one

so we need  something like that

1. add solidify to cutter with small value
2. then just boolean(difference) it the orginal mesh
3 apply boolean
4 remove solidify from curtter ( or cutters)
5.done

yeah I just made it look so complex haha

**Comment by mx1001** [comment]
yeah i cant wait for the cleanup. and removal of old stuff. All the main
dir should be 1 dir deeper except for gui_menus,pies, and panel

**Comment by JacquesLucke** [comment]
Should the operator support multiple cutters directly?

**Comment by mx1001** [comment]
i want to say yes. The cutters should cut into all meshes selected after. I
think that was the intedned behavior. Also that would be cool.

**Comment by niewinny** [comment]
yes we did support multiple cutters to cut into active object

**Comment by JacquesLucke** [comment]
yes I meant the thing @niewinny sais.
@mx1001 what you say seems to be different?

**Comment by niewinny** [comment]
ye lets make it the way it was 
we cant have all at once @mx1001

**Comment by mx1001** [comment]
maybe a toggle option for it it csharpen or ssteps the mesh. On by default
That makes it do it default. But can be turned off in cases where people
want to csplit without sharpening.

http://i.imgur.com/zjnwoKe.gifv

**Comment by JacquesLucke** [comment]
Also what @mx1001 is saying is much more difficult because Blender doesn't support selection order.
Not to say that it is impossible (I implemented it in the animation nodes) but it's not super nice.

**Comment by niewinny** [comment]
lets just go back with what we had, it worked really well for us

**Comment by JacquesLucke** [comment]
when we have multiple cutters, what should the outcome of the operator be?
all in one object?
and what when the user wants to have the things separated? should all the individual pieces be joined or separated?

**Comment by mx1001** [comment]
no multiple cutters right? Only recipients.

The first mesh is the cutter. All meshes selected after that receive cuts
from mesh 1.

The separated meshes are either together based off of the toggle for
separate meshes.

But also csharpened / sstepped depending on its toggle

on a default cslice you should have multiple objects

but the cutter is selcted at the end.

The cutter being selected at the end is important for quick deletion /
reapplication.

**Comment by JacquesLucke** [comment]
no, 
we can have multiple cutters and one target object are the other way around, BUT the object will be alone is the last one you select, because we have the separation in selected_objects and active_object.
The last object you select is the active_object.

**Comment by mx1001** [comment]
hmmm. Adrian what do you say. You invented this one haha.

**Comment by niewinny** [comment]
we ware just using simple split for all separated meshes before,

it was not perfect but I had no idea how to go about it, and it worked quite well for the workflow

**Comment by niewinny** [comment]
like in blender edit mode P->separate by loose parts

**Comment by niewinny** [comment]
oh and for that multiple behavior as i said above lets just make it all selection to cut into active one like it was before. it worked really well

**Pull request merged**
