### PR TITLE
Modals

### PR DESCRIPTION
**Pull request by niewinny**
removed old stuff that we are not going to use anymore and moved new operators to separate files.

We need to upgrade pies and panels to use new operators !!!

Also:
1. bevel and q-array supports Spacebar to accept 
2. bevel now works with smaller values when holding shift

### CODE REVIEW

**Comment by JacquesLucke** [comment]
Can you try to cleanup the imports so that you only import the thinks that are really needed in the file?

For example I know for sure that you don't need "from random import choice" anywhere

**Comment by niewinny** [comment]
oh Ye I just copied it all, will look at it

**Comment by niewinny** [comment]
@mx1001 next time if there are problems let me fix it first haha

and I think overlays do not work now... but I didn't change it
I'm looking at it

**Comment by niewinny** [comment]
ok so if I put he files in modlas folder drawing overlays no longer work, on main folder it is just fine.
Am I missing something?  can't I just move it in

**Comment by mx1001** [comment]
sorry!

**Pull request merged**
